int beam(int row, int col, char[][] grid) {
  if (row == grid.length) {
    return 0;
  }
  var line = grid[row];
  return switch (line[col]) {
    case '|' -> 0;
    case '.' -> {
      line[col] = '|';
      yield beam(row + 1, col, grid);
    }
    /*case '^'*/ default ->  1 + beam(row, col - 1, grid) + beam(row, col + 1, grid);
  };
}

void main() {
  var input = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """;

   var grid = input.lines().map(String::toCharArray).toArray(char[][]::new);
   var start = new String(grid[0]).indexOf('S');
   var count = beam(1, start, grid);
   IO.println(count);
}
