void main() {
  var input = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """;

   var lines = input.lines().toList();
   var start = lines.getFirst().indexOf('S');
  var counter = new Object() { int count; };
  lines.stream()
      .gather(Gatherers.fold(() -> Set.of(start),
          (set, l) -> set.stream()
              .flatMap(index -> l.charAt(index) == '^' ?
                  Stream.of(index - 1, index + 1, counter.count++).limit(2):
                  Stream.of(index))
              .collect(Collectors.toSet())))
      .findFirst().orElseThrow();
  IO.println(counter.count);
}
