void main() {
  var input = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """;

   var lines = input.lines().toList();
   var start = lines.getFirst().indexOf('S');
   var sum = lines.stream()
       .gather(Gatherers.fold(() -> Set.of(Map.entry(start, 0)),
           (entries, l) -> entries.stream()
               .flatMap(e -> l.charAt(e.getKey()) == '^' ?
                   Stream.of(Map.entry(e.getKey() - 1, e.getValue()), Map.entry(e.getKey() + 1, 1)) :
                   Stream.of(e))
               .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue, Integer::sum)).entrySet()))
       .findFirst().orElseThrow().stream().mapToInt(Map.Entry::getValue).sum();
   IO.println(sum);
}
